---
title: "Explore our PISA standardised scores"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
    includes:
      before_body: header.html
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(forcats)
library(plotly)
library(ggthemes)
load("pisa_au.rda")
catvars <- c("state", "schtype", "yr", "birthmonth", "gender")
realvars <- c("math", "science", "read")
```


Outputs {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Boxplots

```{r}
fillRow(height = 600, flex = c(2, 4),
  sidebarPanel(
      selectInput('x', 'X', catvars),
      selectInput('y', 'Y', realvars),
      selectInput('color', 'Color', c('None', catvars)),
      width = 10
  ),
  plotlyOutput("boxplots", height = "100%")
)

output$boxplots <- renderPlotly({
  p1 <- ggplot(pisa_au, aes_string(x = input$x, y = input$y)) +
    geom_boxplot() +
    ggtitle("Test")
  
  if (input$color != 'None')
    p1 <- p1 + aes_string(fill = input$color)

  ggplotly(p1) %>% 
    layout(boxmode = "group", legend = list(x = 0, y = 0, orientation = 'h'))
})
```

### Scatterplot

```{r}
fillRow(height = 600, flex = c(2, 4),
  sidebarPanel(
      selectInput('x2', 'X', realvars, "read"),
      selectInput('y2', 'Y', realvars, "math"),
      selectInput('color2', 'Color', c('None', catvars)),
      sliderInput('alpha', 'Alpha', 0, 1, 1, 0.05),
      width = 10
  ),
  plotlyOutput("scatterplot", height = "100%")
)

output$scatterplot <- renderPlotly({
  p2 <- ggplot(pisa_au, aes_string(x = input$x2, y = input$y2)) +
    geom_point(alpha = input$alpha) +
    theme(aspect.ratio = 1)
  
  if (input$color2 != 'None')
    p2 <- p2 + aes_string(colour = input$color2)

  ggplotly(p2) %>% 
    layout(legend = list(x = 0, y = 0, orientation = 'h'))
})
```

